# ==============================
# Georef (ubicaciones Argentina)
# ==============================
georef.api.base-url=https://apis.datos.gob.ar/georef/api

# ==============================
# DB
# ==============================
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.wekvnrjqngbdelejudyx
spring.datasource.password=Avellaneda.245
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# 🔥 CLAVE
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==============================
# FIX pooler Supabase

# ==============================
spring.jpa.properties.hibernate.statement_cache.size=0
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# ==============================
# Hikari
# ==============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000