# ==============================
# CONFIGURACIÓN DE BASE DE DATOS
# ==============================

# URL de conexión JDBC hacia PostgreSQL (Supabase en este caso)
# Formato: jdbc:postgresql://HOST:PUERTO/NOMBRE_BASE
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
# Usuario de la base de datos
spring.datasource.username=postgres.wekvnrjqngbdelejudyx

# Contraseña del usuario (NO dejar hardcodeado en producción)
spring.datasource.password=Avellaneda.245

# Driver JDBC que se utiliza para conectarse a PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuración de HikariCP (pool de conexiones)
spring.datasource.hikari.maximum-pool-size=3

# ==============================
# CONFIGURACIÓN JPA / HIBERNATE
# ==============================

# Estrategia de generación de esquema:
# update   -> crea o modifica tablas automáticamente
# validate -> solo valida que coincidan con las entidades (recomendado más adelante)
# create   -> borra y crea todo cada vez
spring.jpa.hibernate.ddl-auto=update

# Muestra en consola las consultas SQL que ejecuta Hibernate
spring.jpa.show-sql=true

# Formatea el SQL para que sea más legible en consola
spring.jpa.properties.hibernate.format_sql=true

# Desactiva el Open Session in View (buena práctica)
# Evita que Hibernate mantenga la sesión abierta hasta la capa web
spring.jpa.open-in-view=false
